# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e3b2478d471c8b4c76330bb44c4139ae"
name = "smart-bar"
handle = "smart-bar-1"
application_url = "https://count-turns-projectors-usual.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://count-turns-projectors-usual.trycloudflare.com/auth/callback", "https://count-turns-projectors-usual.trycloudflare.com/auth/shopify/callback", "https://count-turns-projectors-usual.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
